server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

spring:
  profiles:
    active: native
  data:
    mongodb:
      uri: mongodb://miguel:admin@127.0.0.1:27017
      database: produto
      auto-index-creation: true
